[package]
name = "kotaru-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.11.1", features = ["full"] }
clap = { version = "4.5.31", features = ["derive"] }
dirs = "5.0"

